import os.path
import pandas as pd
from taxUtils import read_json_file

# Define the data directory
data_directory = "../data"

# Load the user wallets to know the wallet identifier
user_wallets = read_json_file(os.path.join(data_directory, "input", "user_wallets.json"))
user_first_wallet = list(user_wallets.keys())[0]

# Load the operations csv generated by walletOperations.py
operations_file = os.path.join(data_directory, "output", f"operations_{user_first_wallet}.csv")
operations = pd.read_csv(operations_file, parse_dates=["timestamp"], keep_default_na=False)

# Helper function to guess the asset name for the operation

def _get_asset(row):
    return row["token_name"] if row.get("token_name") and row["token_name"] != "" else "XTZ"

# Map our operation kind to a Blockpit transaction type

def _map_type(kind: str) -> str:
    kind = kind.lower()
    if kind == "send tez":
        return "Withdrawal"
    if kind == "receive tez":
        return "Deposit"
    if kind == "receive tez from staking" or kind in ["baking", "endorsing reward"]:
        return "Staking Reward"
    if any(word in kind for word in ["swap", "sell", "buy", "collect", "mint", "burn"]):
        return "Trade"
    return "Other"

# Build the different columns expected by Blockpit

def build_blockpit_frame(df: pd.DataFrame) -> pd.DataFrame:
    assets = df.apply(_get_asset, axis=1)
    incoming_asset = df.apply(lambda r: _get_asset(r) if r["received_amount"] > 0 else "", axis=1)
    outgoing_asset = df.apply(lambda r: _get_asset(r) if r["spent_amount"] > 0 else "", axis=1)

    blockpit_df = pd.DataFrame({
        "Date": df["timestamp"],
        "Type": df["kind"].apply(_map_type),
        "Outgoing Asset": outgoing_asset,
        "Outgoing Amount": df["spent_amount"].where(df["spent_amount"] > 0, ""),
        "Incoming Asset": incoming_asset,
        "Incoming Amount": df["received_amount"].where(df["received_amount"] > 0, ""),
        "Fee Asset": df.apply(lambda r: "XTZ" if r["spent_fees"] > 0 else "", axis=1),
        "Fee": df["spent_fees"].where(df["spent_fees"] > 0, ""),
        "Comment": df["comment"],
    })
    return blockpit_df

blockpit_df = build_blockpit_frame(operations)

# Save the dataframe to csv
output_file = os.path.join(data_directory, "output", f"blockpit_import_{user_first_wallet}.csv")
blockpit_df.to_csv(output_file, index=False)
print(f"Blockpit CSV saved to {output_file}")
